'use client'

import Dashboard from '@/components/dashboard/Dashboard'
import { QueryResponse } from '@/lib/types'

interface ResultsPageProps {
  prompt: string
  response: QueryResponse | null
  revealed: boolean
  onReveal: () => void
  onReset: () => void
}

function formatEventLabel(eventType?: string, status?: string) {
  if (eventType === 'planner_status') {
    return status === 'completed' ? 'Planner completed' : 'Planner running'
  }

  if (eventType === 'agent_status') {
    return status ? `${status[0].toUpperCase()}${status.slice(1)}` : 'Agent update'
  }

  return eventType || 'Update'
}

export default function ResultsPage({ prompt, response, revealed, onReveal, onReset }: ResultsPageProps) {
  const highlights = response?.presentation?.summary?.highlights || []
  const quickActions = response?.presentation?.quick_actions || []
  const timeline = response?.agent_execution?.timeline || []
  const summaryTitle = response?.presentation?.summary?.title || 'TerpAI completed the workflow and returned the result below.'

  if (!revealed) {
    return (
      <div className="relative min-h-screen overflow-hidden bg-[#F8FAFC] px-4 py-10 text-[#111827]">
        <div className="absolute top-0 right-0 -mr-32 -mt-32 h-72 w-72 rounded-full bg-[#E31937]/8 blur-3xl" />
        <div className="absolute bottom-0 left-0 -ml-40 -mb-40 h-80 w-80 rounded-full bg-[#FFB81C]/8 blur-3xl" />

        <div className="relative mx-auto w-full max-w-4xl space-y-8">
          <div className="rounded-[36px] border border-[#E31937]/10 bg-white/95 p-8 shadow-[0_35px_100px_-45px_rgba(227,25,55,0.3)] backdrop-blur-xl">
            <div className="space-y-4 text-center">
              <p className="text-sm uppercase tracking-[0.28em] text-[#92400E]">Workflow complete</p>
              <h2 className="text-4xl font-black">Aggregator summary is ready</h2>
              <p className="mx-auto max-w-2xl text-base leading-7 text-[#475569]">
                The task planner, selected agents, and aggregator have all finished. Click the button below to open the final summary generated by the backend.
              </p>
            </div>

            <div className="mt-10 grid gap-6 md:grid-cols-3">
              <div className="rounded-[28px] border border-[#E31937]/10 bg-[#FFFBEB] p-6 shadow-sm">
                <p className="text-xs uppercase tracking-[0.3em] text-[#92400E]">Prompt</p>
                <p className="mt-3 text-base font-semibold text-[#111827]">{prompt}</p>
              </div>
              <div className="rounded-[28px] border border-[#E31937]/10 bg-white p-6 shadow-sm md:col-span-2">
                <p className="text-xs uppercase tracking-[0.3em] text-[#475569]">Backend ready</p>
                <p className="mt-3 text-base leading-7 text-[#111827]">{summaryTitle}</p>
                <p className="mt-3 text-sm text-[#475569]">
                  The summary is hidden until you choose to view it. This keeps the workflow page focused on live execution first.
                </p>
              </div>
            </div>

            <div className="mt-10 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-center">
              <button
                onClick={onReveal}
                className="inline-flex items-center justify-center rounded-[28px] bg-[#E31937] px-6 py-3 text-sm font-semibold text-white transition hover:bg-[#c61631]"
              >
                Show aggregator summary
              </button>
              <button
                onClick={onReset}
                className="inline-flex items-center justify-center rounded-[28px] border border-[#E31937] bg-white px-6 py-3 text-sm font-semibold text-[#E31937] transition hover:bg-[#FEF2F2]"
              >
                Start another query
              </button>
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="relative min-h-screen overflow-hidden bg-[#F8FAFC] px-4 py-10 text-[#111827]">
      {/* Animated background blobs */}
      <div
        className="absolute top-0 right-0 -mr-32 -mt-32 h-72 w-72 rounded-full bg-[#E31937]/8 blur-3xl"
      />
      <div
        className="absolute bottom-0 left-0 -ml-40 -mb-40 h-80 w-80 rounded-full bg-[#FFB81C]/8 blur-3xl"
      />

      <div className="relative mx-auto w-full max-w-6xl space-y-8">
        <div
          className="rounded-[36px] border border-[#E31937]/10 bg-white/95 p-8 shadow-[0_35px_100px_-45px_rgba(227,25,55,0.3)] backdrop-blur-xl"
        >
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p
                className="text-sm uppercase tracking-[0.28em] text-[#92400E]"
              >
                Final campus answer
              </p>
              <h2
                className="mt-2 text-4xl font-black"
              >
                Aggregated Results
              </h2>
              <p
                className="mt-3 max-w-2xl text-base leading-7 text-[#475569]"
              >
                The backend ran the requested agents, aggregated their outputs, and returned the final student-ready result.
              </p>
            </div>
            <button
              onClick={onReset}
              className="inline-flex items-center justify-center rounded-[28px] border border-[#E31937] bg-white px-6 py-3 text-sm font-semibold text-[#E31937] transition hover:bg-[#FEF2F2]"
            >
              Ask another question
            </button>
          </div>

          <div className="mt-10 grid gap-6 lg:grid-cols-3">
            <div
              className="rounded-[32px] border border-[#E31937]/10 bg-[#FFFBEB] p-6 shadow-sm hover:shadow-lg transition-shadow"
            >
              <p
                className="text-xs uppercase tracking-[0.3em] text-[#92400E]"
              >
                Campus prompt
              </p>
              <p className="mt-4 text-lg font-semibold text-[#111827]">
                {prompt}
              </p>
            </div>

            <div
              className="rounded-[32px] border border-[#E31937]/10 bg-white p-6 shadow-sm hover:shadow-lg transition-shadow"
            >
              <p
                className="text-xs uppercase tracking-[0.3em] text-[#475569]"
              >
                Final answer
              </p>
              <p className="mt-4 text-base leading-7 text-[#111827]">
                {summaryTitle}
              </p>
              {highlights.length > 0 && (
                <ul className="mt-4 space-y-2 text-sm text-[#475569]">
                  {highlights.slice(0, 4).map((highlight) => (
                    <li key={highlight} className="rounded-2xl bg-[#F8FAFC] px-4 py-3">
                      {highlight}
                    </li>
                  ))}
                </ul>
              )}
            </div>

            <div
              className="rounded-[32px] border border-[#E31937]/10 bg-[#F0F9FF] p-6 shadow-sm hover:shadow-lg transition-shadow"
            >
              <p
                className="text-xs uppercase tracking-[0.3em] text-[#1D4ED8]"
              >
                Ready to use
              </p>
              <h3 className="mt-4 text-lg font-semibold text-[#111827]">Campus-ready summary</h3>
              <p className="mt-3 text-sm text-[#475569]">
                Perfect for quick decisions on dining, directions, and campus activities.
              </p>
            </div>
          </div>

          <div
            className="mt-8 rounded-[32px] border border-[#E31937]/10 bg-white p-6 shadow-sm"
          >
            <h3 className="text-xl font-semibold text-[#111827]">Workflow trace</h3>
            <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">
              {timeline.slice(0, 6).map((event, index) => (
                <div key={`${event.type || 'event'}-${index}`} className="rounded-2xl border border-[#E5E7EB] bg-[#F8FAFC] p-4">
                  <p className="text-xs uppercase tracking-[0.25em] text-[#92400E]">
                    {formatEventLabel(event.type, event.status)}
                  </p>
                  <p className="mt-2 text-sm font-medium text-[#111827]">
                    {event.agent || event.work || event.message || 'Backend update'}
                  </p>
                </div>
              ))}
            </div>

            <h3 className="mt-8 text-xl font-semibold text-[#111827]">TerpAI dashboard</h3>
            <div className="mt-4 space-y-5">
              {response ? <Dashboard data={response} /> : <p className="text-sm text-[#475569]">Waiting for backend data...</p>}
            </div>

            {quickActions.length > 0 && (
              <div className="mt-8 rounded-[28px] bg-[#FFFBEB] p-5 shadow-sm">
                <p className="text-sm uppercase tracking-[0.25em] text-[#92400E]">Quick actions</p>
                <div className="mt-4 flex flex-wrap gap-3">
                  {quickActions.map((action, index) => (
                    <a
                      key={`${action.label || 'action'}-${index}`}
                      href={action.target || '#'}
                      target={action.target ? '_blank' : undefined}
                      rel={action.target ? 'noreferrer' : undefined}
                      className="rounded-full bg-white px-4 py-2 text-sm font-semibold text-[#E31937] shadow-sm transition hover:bg-[#FFF7F7]"
                    >
                      {action.label || 'Open'}
                    </a>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
